name: Sportzy
description: Sportzy

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: 1.0.4
  cross_file: ^0.3.3+7
  permission_handler: 10.1.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  uuid: ^3.0.7
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/profile_pics/
    - assets/community_pics/
    - assets/images/
    