
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// Possivelmente contém configurações e opções relacionadas à integração com o Firebase, um serviço de desenvolvimento de aplicativos fornecido pela Google. Pode incluir configurações de autenticação, banco de dados, notificações, etc.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk27WAVeYAnx8jLoztDKtoSuiZ-Xv3uQk',
    iosBundleId: 'com.codegemz.flutlab.login',
    appId: '1:214546683267:ios:6b980c6fc946fa2d2d92b6',
    storageBucket: 'flutter-simple-login.appspot.com',
    messagingSenderId: '214546683267',
    iosClientId: '214546683267-etcbvvioresh40giajbrrmqni1kkokbs.apps.googleusercontent.com',
    projectId: 'flutter-simple-login'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzw_YFW_JdW4ICbt66re-JjWgd64hjbs',
    appId: '1:214546683267:android:569c65b7a3711ffa2d92b6',
    messagingSenderId: '214546683267',
    projectId: 'flutter-simple-login',
    storageBucket: 'flutter-simple-login.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBrXjXT5Pwl-nDBSEFwrs6U1aBMdunV0I',
    authDomain: 'flutter-simple-login.firebaseapp.com',
    projectId: 'flutter-simple-login',
    storageBucket: 'flutter-simple-login.appspot.com',
    messagingSenderId: '214546683267',
    appId: '1:214546683267:web:a47fb660458180f92d92b6'
  );
}
